name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        tarball:
          - https://github.com/nim-lang/nightlies/releases/download/latest-version-1-2/source.tar.xz
    name: ${{ matrix.os }} - ${{ matrix.tarball }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Nim
        shell: bash
        run: |
          curl -L -o source.tar.xz ${{ matrix.tarball }}
          mkdir -p nimtmp
          tar xf source.tar.xz -C nimtmp
          cd nimtmp
          mv $(ls) ../nim
          cd ../nim
          pwd
          sh build.sh
          bin/nim c koch
          ./koch boot -d:release
          echo "$(pwd)/bin" >> $GITHUB_PATH
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH
          ls "$(pwd)/bin/"
      - name: Add nim/bin to PATH
        # Doing this with Python so that it works in Windows/macOS/Linux
        run: python -c 'import os; print(os.path.abspath(os.path.join("./nim/bin")))' >> $GITHUB_PATH
      - run: nim --version      
      - name: Run nim c -r tester
        run: |
          cd tests
          nim c -r tester
      - run: ./src/nimble install -y
